version: '3.8' # Docker Engine release 18.02.0+

services:
  flask:
    build: ./
    container_name: linebot
    # restart: always
    command: gunicorn --bind 0.0.0.0:5000 --chdir src app:app
    env_file: .env
    ports:
      - '5000:5000'

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
volumes:
  redis-data:
