version: '3.8' # Docker Engine release 18.02.0+

services:
  flask:
    build: ./
    container_name: linebot
    # restart: always
    command: gunicorn --bind 0.0.0.0:5000 --chdir src app:app
    env_file: .env
    ports:
      - '5000:5000'
