"""每日交易資料

Revision ID: 3c32ac23f8a2
Revises: 7d255bdcb098
Create Date: 2021-10-23 15:19:22.151280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c32ac23f8a2'
down_revision = '7d255bdcb098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily_informations',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('trading_volume', sa.Integer(), nullable=True),
    sa.Column('trading_money', sa.Integer(), nullable=True),
    sa.Column('trading_turnover', sa.Integer(), nullable=True),
    sa.Column('current_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_stock_daily_informations_stock_id'), 'stock_daily_informations', ['stock_id'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stock_daily_informations_stock_id'), table_name='stock_daily_informations')
    op.drop_table('stock_daily_informations')
    # ### end Alembic commands ###
